<?php

/**
 * Implements hook_form_alter().
 */
function recetas_core_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  //print_r($form);
  $form['first_recipe'] = [
    '#weight' => 100,
    '#theme' =>'recetas_core_vars',
    '#forums' =>t('hello'),
    '#parents' =>'mundo',
    '#tid' =>'blalballal',
  ];
}

/**
 * Implements hook_theme().
 */
function recetas_core_theme($existing, $type, $theme, $path)
{
  return [
    'recetas_core_vars'=> [
      'variables' => ['forums' => NULL, 'parents' => NULL, 'tid' => NULL],
    ],
    'recetas_core'=> [
      'render element' =>'element',
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function recetas_core_preprocess_recetas_core_vars(&$variables )
{
$variables['forums']= t("hello");
}
